# Generated by Django 3.0.2 on 2020-02-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcategory',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
