# Generated by Django 3.0.2 on 2020-03-17 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=1)),
                ('toolCategory', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tools.ToolCategory')),
            ],
        ),
    ]
