# Generated by Django 3.0.2 on 2020-02-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_toolcategory_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolcategory',
            old_name='count',
            new_name='available',
        ),
    ]
