# Generated by Django 3.0.2 on 2020-03-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='duedates',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
