# Generated by Django 2.2.6 on 2020-03-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_duedates_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('date_bought', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tools', models.CharField(max_length=500)),
            ],
        ),
    ]
