# Generated by Django 3.0.2 on 2020-03-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20200218_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcategory',
            name='tool_image',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
