# Generated by Django 2.2.6 on 2020-03-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20200218_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcategory',
            name='dueDates',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
