# Generated by Django 2.2.6 on 2020-03-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='state',
            field=models.CharField(choices=[('in', 'Checked In'), ('out', 'Checked Out')], default='out', max_length=2),
        ),
    ]
