# Generated by Django 2.2 on 2020-03-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_toolcategory_tool_image'),
        ('tools', '0005_auto_20200311_0321'),
    ]

    operations = [
    ]
