# Generated by Django 2.2.6 on 2020-03-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_history_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='state',
            field=models.CharField(default='Checked Out', max_length=2),
        ),
    ]
