# Generated by Django 2.2 on 2020-04-09 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_shoppingcart_tool_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date_returned',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
