# Generated by Django 2.2 on 2020-04-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_history_date_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_returned',
            field=models.DateTimeField(blank=True),
        ),
    ]
