# Generated by Django 2.2 on 2020-04-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_auto_20200408_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
